import Head from "next/head";
import Navbar from "./../components/Navbar";
import Banner from "./../components/Banner";
import { Product } from "../type";
import Products from "./../components/Products";
import Footer from "./../components/Footer";
import TopFooter from './../components/TopFooter';

interface Props {
  productData: Product;
}

export default function Home({ productData }: Props) {
  //console.log(productData);
  return (
    <>
      <Head>
        <title> S⚽️CER ST⚽️RE </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-lightBlue">
        <div className="max-w-contentContainer mx-auto bg-white">
          <Banner />
          <Products productData={productData} />
        </div>
      </main>
    </>
  );
}

// =================== SSR data fetching start here ===================================
export const getServerSideProps = async () => {
  const productData = await (
    await fetch(`${process.env.NEXTAYTH_URL}/api/productData`)
  ).json();

  return {
    props: { productData },
  };
};
